## env dev

#用来测试bus总线同步
suffix: consumer-suffix-dev

server:
  port: 7070

spring:
  profiles: dev
  application:
    name: consumer

eureka:
  client:
    service-url:
      defaultZone: http://eureka8001.com:8001/eureka

# 开启Feign对Hystrix的支持
feign:
  hystrix:
    enabled: true

---
## env test

#用来测试bus总线同步
suffix: consumer-suffix-test

server:
  port: 9090

spring:
  profiles: test
  application:
    name: consumer

eureka:
  client:
    service-url:
      defaultZone: http://eureka8002.com:8002/eureka

# 开启Feign对Hystrix的支持
feign:
  hystrix:
    enabled: true