## env dev

#用来测试bus总线同步
flag: provider-flag-dev

server:
  port: 8084

# 设置Spring-Data-JPA
spring:
  profiles: dev
  application:
    name: provider
  jpa:
    # 指定在Spring容器启动时是否自动建表，默认为false
    generate-ddl: true
    # 指定是否在控制台显示其执行的SQL语句，默认false
    show-sql: true
    # 指定应用重启时是否重新创建更新表
    hibernate:
      ddl-auto: update

  # 配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/architect?useUnicode=true&characterEncoding=utf8'
    username: root
    password: xiaohuoban

# 指定Eureka服务中心
eureka:
  client:
    service-url:
      defaultZone: http://eureka8001.com:8001/eureka

---
## env test

#用来测试bus总线同步
flag: provider-flag-test

server:
  port: 8085

# 设置Spring-Data-JPA
spring:
  profiles: test
  application:
    name: provider
  jpa:
    # 指定在Spring容器启动时是否自动建表，默认为false
    generate-ddl: true
    # 指定是否在控制台显示其执行的SQL语句，默认false
    show-sql: true
    # 指定应用重启时是否重新创建更新表
    hibernate:
      ddl-auto: update

  # 配置数据源
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: 'jdbc:mysql://localhost:3306/architect?useUnicode=true&characterEncoding=utf8'
    username: root
    password: xiaohuoban

# 指定Eureka服务中心
eureka:
  client:
    service-url:
      defaultZone: http://eureka8002.com:8002/eureka
